import { describe, expect, it } from 'vitest';
import {
  AGENT_MISSION_BOOTSTRAP_RECEIPT_ATTEMPTS,
  AGENT_MISSION_BOOTSTRAP_RECEIPT_REQUEST_TIMEOUT_MS,
  AGENT_MISSION_BOOTSTRAP_RECEIPT_REQUIRED_BUDGET_MS,
  AGENT_MISSION_BOOTSTRAP_RECEIPT_SAFETY_MARGIN_MS,
} from './agent-mission-bootstrap-policy';

describe('AgentMission bootstrap receipt policy', () => {
  it('réserve deux tentatives réseau et une marge explicite', () => {
    expect(AGENT_MISSION_BOOTSTRAP_RECEIPT_ATTEMPTS).toBe(2);
    expect(AGENT_MISSION_BOOTSTRAP_RECEIPT_REQUEST_TIMEOUT_MS).toBe(4_000);
    expect(AGENT_MISSION_BOOTSTRAP_RECEIPT_SAFETY_MARGIN_MS).toBe(1_000);
    expect(AGENT_MISSION_BOOTSTRAP_RECEIPT_REQUIRED_BUDGET_MS).toBe(
      AGENT_MISSION_BOOTSTRAP_RECEIPT_ATTEMPTS
      * AGENT_MISSION_BOOTSTRAP_RECEIPT_REQUEST_TIMEOUT_MS
      + AGENT_MISSION_BOOTSTRAP_RECEIPT_SAFETY_MARGIN_MS,
    );
  });
});
