import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { headers } from 'next/headers';
import type { ReactNode } from 'react';
import { tc } from '@/src/cabinet/i18n';
import '@bob/tokens/variables.css';
import './globals.css';

const displayFont = localFont({
  display: 'swap',
  preload: true,
  src: [
    {
      path: '../../../node_modules/@expo-google-fonts/schibsted-grotesk/700Bold/SchibstedGrotesk_700Bold.ttf',
      style: 'normal',
      weight: '700',
    },
    {
      path: '../../../node_modules/@expo-google-fonts/schibsted-grotesk/800ExtraBold/SchibstedGrotesk_800ExtraBold.ttf',
      style: 'normal',
      weight: '800',
    },
  ],
  variable: '--font-schibsted',
});

const textFont = localFont({
  display: 'swap',
  preload: true,
  src: [
    {
      path: '../../../node_modules/@expo-google-fonts/hanken-grotesk/500Medium/HankenGrotesk_500Medium.ttf',
      style: 'normal',
      weight: '500',
    },
    {
      path: '../../../node_modules/@expo-google-fonts/hanken-grotesk/600SemiBold/HankenGrotesk_600SemiBold.ttf',
      style: 'normal',
      weight: '600',
    },
    {
      path: '../../../node_modules/@expo-google-fonts/hanken-grotesk/700Bold/HankenGrotesk_700Bold.ttf',
      style: 'normal',
      weight: '700',
    },
  ],
  variable: '--font-hanken',
});

export const metadata: Metadata = {
  title: tc('cabinet.metadata.title'),
  description: tc('cabinet.metadata.description'),
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  // A nonce is generated by proxy.ts for every document request. Reading the
  // request headers opts the route into dynamic rendering so Next can extract
  // that nonce from the request CSP and attach it to its bootstrap scripts.
  await headers();

  return (
    <html className={`${displayFont.variable} ${textFont.variable}`} data-bob-theme="marine" lang="fr">
      <body>
        <a className="skip-link" href="#main-content">{tc('cabinet.accessibility.skip')}</a>
        {children}
      </body>
    </html>
  );
}
