import { readFileSync, readdirSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const WEB_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const RAW_COLOR = /#[0-9a-f]{3,8}\b|rgba?\s*\(/i;

function sourceFiles(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) return sourceFiles(path);
    return /\.(?:css|ts|tsx)$/.test(entry.name) ? [path] : [];
  });
}

describe('design system web Bob Pro', () => {
  it('interdit toute palette hex/rgb parallèle dans les sources applicatives', () => {
    const violations = sourceFiles(join(WEB_ROOT, 'app'))
      .filter((path) => RAW_COLOR.test(readFileSync(path, 'utf8')))
      .map((path) => relative(WEB_ROOT, path));

    // Les documents imprimables utilisent aussi les variables Bob ; aucune exception couleur
    // n'est autorisée, y compris dans les prototypes historiques import/dossier/lettre.
    expect(violations).toEqual([]);
  });

  it('consomme le CSS généré et les deux familles typographiques Bob', () => {
    const layout = readFileSync(join(WEB_ROOT, 'app/layout.tsx'), 'utf8');
    const proxy = readFileSync(join(WEB_ROOT, 'proxy.ts'), 'utf8');
    const generated = readFileSync(resolve(WEB_ROOT, '../../packages/tokens/src/variables.css'), 'utf8');

    expect(layout).toContain("import '@bob/tokens/variables.css'");
    expect(layout).toContain("from 'next/font/local'");
    expect(layout).not.toContain("from 'next/font/google'");
    expect(layout).toContain('@expo-google-fonts/schibsted-grotesk');
    expect(layout).toContain('@expo-google-fonts/hanken-grotesk');
    expect(layout).toContain("variable: '--font-schibsted'");
    expect(layout).toContain("variable: '--font-hanken'");
    expect(layout).toContain("import { headers } from 'next/headers'");
    expect(layout).toContain('await headers()');
    expect(proxy).toContain("'strict-dynamic'");
    expect(generated).toContain('Generated by scripts/generate-css.mjs from @bob/tokens');
    expect(generated).toContain('--bob-color-ink-900:');
    expect(generated).toContain('--brand-gradient-cta:');
  });

  it('impose la voix Pro @bob/i18n au nouveau rail Slice 0', () => {
    const sliceZeroFiles = [
      'app/cabinet/cabinet-gateway.tsx',
      'app/cabinet/components/app-shell.tsx',
      'app/cabinet/components/team-view.tsx',
    ];
    const visibleJsxLiteral = /<[a-z][^>]*>[ \t]*([A-Za-zÀ-ÿ][^<>{}\n]*)<\/[a-z]/gi;
    const violations = sliceZeroFiles.flatMap((file) => {
      const source = readFileSync(join(WEB_ROOT, file), 'utf8');
      expect(source).toContain("from '@/src/cabinet/i18n'");
      return [...source.matchAll(visibleJsxLiteral)]
        .map((match) => match[1]?.trim())
        .filter((literal): literal is string => Boolean(literal) && literal !== 'B')
        .map((literal) => `${file}: ${literal}`);
    });

    // Les prototypes métier des slices 1–8 seront migrés avec leurs règles et modèles ; le
    // shell/auth/équipe Slice 0, lui, ne tolère déjà plus aucune copy visible en dur.
    expect(violations).toEqual([]);
  });

  it('interdit toute autorité locale ou démonstration dans l’espace cabinet', () => {
    const application = readFileSync(join(WEB_ROOT, 'app/cabinet/cabinet-app.tsx'), 'utf8');
    const gateway = readFileSync(join(WEB_ROOT, 'app/cabinet/cabinet-gateway.tsx'), 'utf8');
    const shell = readFileSync(join(WEB_ROOT, 'app/cabinet/components/app-shell.tsx'), 'utf8');
    const access = readFileSync(join(WEB_ROOT, 'src/cabinet/access.ts'), 'utf8');
    const api = readFileSync(join(WEB_ROOT, 'src/cabinet/api.ts'), 'utf8');
    const cabinetIndex = readFileSync(join(WEB_ROOT, 'src/cabinet/index.ts'), 'utf8');

    expect(application).not.toContain('localStorage');
    expect(application).not.toContain("from '@/src/cabinet/storage'");
    expect(application).toContain('loadCabinetDossierPortfolio');
    expect(application).toContain('dossierTransport.saveDossier');
    expect(application).toContain('dossierTransport.deleteDossier');
    expect(application).toContain('<TeamView key={cabinetId} access={access} />');
    expect(gateway).not.toContain('LocalDemoButton');
    expect(gateway).not.toContain("mode: 'local'");
    expect(access).not.toContain("readonly mode: 'local'");
    expect(shell).not.toContain("access.mode === 'local'");
    expect(api).toContain("from './dossier-validation'");
    expect(api).not.toContain("from './storage'");
    expect(cabinetIndex).not.toContain("export * from './storage'");
  });
});
