import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { themes, toCssVars } from '../dist/index.js';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sourceOutput = resolve(packageRoot, 'src/variables.css');
const distOutput = resolve(packageRoot, 'dist/variables.css');

function declarationBlock(theme) {
  return Object.entries(toCssVars(theme))
    .map(([name, value]) => `  ${name}: ${value};`)
    .join('\n');
}

const css = [
  '/* Generated by scripts/generate-css.mjs from @bob/tokens. Do not edit by hand. */',
  ':root,',
  '[data-bob-theme="marine"] {',
  declarationBlock(themes.marine),
  '}',
  ...Object.entries(themes)
    .filter(([name]) => name !== 'marine')
    .flatMap(([name, theme]) => [
      '',
      `[data-bob-theme="${name}"] {`,
      declarationBlock(theme),
      '}',
    ]),
  '',
].join('\n');

await mkdir(dirname(distOutput), { recursive: true });
await Promise.all([
  writeFile(sourceOutput, css, 'utf8'),
  writeFile(distOutput, css, 'utf8'),
]);
