export const REALTIME_VOICE_SETTINGS = Symbol('REALTIME_VOICE_SETTINGS');
export const OPENAI_REALTIME_CALL_PROVIDER = Symbol('OPENAI_REALTIME_CALL_PROVIDER');
export const REALTIME_ADMISSION = Symbol('REALTIME_ADMISSION');
export const REALTIME_SIDEBAND = Symbol('REALTIME_SIDEBAND');
export const REALTIME_AGENT_TURN = Symbol('REALTIME_AGENT_TURN');
export const REALTIME_ENTITLEMENT = Symbol('REALTIME_ENTITLEMENT');
