export const REALTIME_VOICE_SETTINGS = Symbol('REALTIME_VOICE_SETTINGS');
export const OPENAI_REALTIME_CALL_PROVIDER = Symbol('OPENAI_REALTIME_CALL_PROVIDER');
export const REALTIME_ADMISSION = Symbol('REALTIME_ADMISSION');
export const REALTIME_SIDEBAND = Symbol('REALTIME_SIDEBAND');
export const REALTIME_DURABLE_CONTROLS = Symbol('REALTIME_DURABLE_CONTROLS');
export const REALTIME_AGENT_TURN = Symbol('REALTIME_AGENT_TURN');
export const REALTIME_ENTITLEMENT = Symbol('REALTIME_ENTITLEMENT');
export const MISTRAL_REALTIME_INGRESS_TICKETS = Symbol('MISTRAL_REALTIME_INGRESS_TICKETS');
export const MISTRAL_REALTIME_INGRESS_RUNTIME = Symbol('MISTRAL_REALTIME_INGRESS_RUNTIME');
export const MISTRAL_CONVERSATION_TERMINAL_REPLAY_RUNTIME = Symbol(
  'MISTRAL_CONVERSATION_TERMINAL_REPLAY_RUNTIME',
);
export const MISTRAL_CONVERSATION_RESUME_AUTHORITY = Symbol(
  'MISTRAL_CONVERSATION_RESUME_AUTHORITY',
);
export const MISTRAL_REALTIME_TERMINATION_AUTHORITY = Symbol('MISTRAL_REALTIME_TERMINATION_AUTHORITY');
export const REALTIME_PROVIDER_TERMINATION_REGISTRY = Symbol('REALTIME_PROVIDER_TERMINATION_REGISTRY');
export const REALTIME_SPEECH_SOURCE_POLICY = Symbol('REALTIME_SPEECH_SOURCE_POLICY');
